### ISSUE TITLE
@JsonIgnore missing for JavaBean with map like type

### ISSUE THREAD

**Issue by katmatt** [vrapio/rmf-codegen#15]
With our `LocalizedString` raml type:
```
  LocalizedString:
    type: object
    properties:
      /^[a-z]{2}(-[A-Z]{2})?$/:
        type: string
```
we generate the JavaBean `LocalizedString` which can be correctly deserialized. But serializing a `LocalizedString` object leads to the following json:
```
{
   "values": {
      "en": "test"
   }
}
```
This can be fixed by adding the `@JsonIgnore` annotation to the generated values field:
```
  @JsonIgnore
  private Map<String, String> values = new HashMap();
```
We should add this to our `BeanGenerator`.
