### ISSUE TITLE
Java codegen should ignore nil in union types

### ISSUE THREAD

**Issue by katmatt** [vrapio/rmf-codegen#19]
If an union type just consist of a type and `nil`, then our code generator can skip the `nil`type and just generate code for the single type. This is useful with the following type:
```yaml
  Attributes:
    properties:
      //:
        description: |
          The name of the attribute is given by the key and shouldn't be set on the attribute itself.
          And since this property will be represented as a map, we can set individual attributes to null
          to delete them (following JSON Merge Patch semantic).
        type: Attribute | nil
```
