### ISSUE TITLE
Add support for documenting enum values to java model

### ISSUE THREAD

**Issue by katmatt** [vrapio/rmf-codegen#54]
Add support for documenting enum values to java model. 
We should specify the enum values doc like this:
```
annotationTypes:
  doc:
    description: |
      Allows to add doc/description to an enum value.
    type: string
types:
  ResourceType:
    type: string
    enum:
      - value: channel
        (doc): The channel resource type.
      - cart-discount
      - category
      - customer
      - customer-group
      - order
      - price
      - product
      - product-type
      - product-variant
      - product-variant-patch
      - shipping-method
      - state
      - tax-category
```
