### ISSUE TITLE
Generated joi schema should support cyclic dependencies

### ISSUE THREAD

**Issue by katmatt** [vrapio/rmf-codegen#88]
Our current joi code generator runs in a stackoverflow error for a recursive RAML type:
```yaml
types:
  CircularType:
    properties:
      self: CircularType
```
